Update /root contents.

diff --git a/root/bin/fw-adduser b/root/bin/fw-adduser
--- a/root/bin/fw-adduser
+++ b/root/bin/fw-adduser
@@ -1,33 +1,86 @@
 #!/bin/sh
 
-while getopts qm:u:p: arg
+Help() {
+    echo >&2 ""
+    echo >&2 "Usage: fw-adduser [options] username password"
+    echo >&2 ""
+    echo >&2 "Optional arguments:"
+    echo >&2 ""
+    echo >&2 "-q          Quiet"
+    echo >&2 "-m manager  Set 'manager' field"
+    echo >&2 "-e email    Set 'mail' field"
+    echo >&2 "-r email    Set 'fwRecoveryMail' field"
+    echo >&2 ""
+    exit 1
+}
+
+while getopts qm:e:r: arg
 do
     case $arg in
         (q) quiet=yes ;;
         (m) manager=$OPTARG ;;
-        (u) username=$OPTARG ;;
-        (p) password=$OPTARG ;;
+        (e) email=$OPTARG ;;
+        (r) recoveryMail=$OPTARG ;;
+        (*) Help
     esac
 done
 
-if [ -z "$manager" ] || [ -z "$username" ] || [ -z "$password" ]
+shift $((OPTIND - 1))
+
+if [ $# -ne 2 ]
 then
-    echo >&2 "Usage: fw-adduser -m manager -u username -p password"
+    Help
+fi
+
+username=$1
+password=$2
+
+for cn in "$manager" "$username"
+do
+    if printf %s "$cn" | grep -q '^[^a-zA-Z]\|[^a-zA-Z0-9]'
+    then
+        echo >&2 "Invalid username: $cn"
+        echo >&2 "Usernames must begin with a letter,"
+        echo >&2 "and only contain letters and digits."
+        exit 1
+    fi
+done
+
+if printf %s "$password" | grep -q '[^a-zA-Z0-9]'
+then
+    echo >&2 "Invalid password: $password"
+    echo >&2 "Password must only contain letters and digits."
     exit 1
 fi
 
 lcaseUsername=$(printf '%s' "$username" | /usr/bin/tr '[:upper:]' '[:lower:]')
 
+if [ "$email" = "" ]
+then
+    email=$lcaseUsername@feministwiki.org
+fi
+
+if [ "$recoveryMail" = "" ]
+then
+    recoveryMail=$email
+fi
+
+if [ "$manager" = "" ]
+then
+    manager=SocJusWiz
+fi
+
 dn="cn=$username,ou=members,dc=feministwiki,dc=org"
 
 input="dn: $dn
 changetype: add
-objectClass: inetOrgPerson
+objectClass: fwMember
 cn: $username
 uid: $username
-sn: -
+sn: $username
 userPassword: $password
-mail: $lcaseUsername@feministwiki.org
+mail: $email
+fwRecoveryMail: $recoveryMail
 manager: cn=$manager,ou=members,dc=feministwiki,dc=org
 
 dn: cn=members,ou=groups,dc=feministwiki,dc=org
diff --git a/root/bin/fw-deluser b/root/bin/fw-deluser
--- a/root/bin/fw-deluser
+++ b/root/bin/fw-deluser
@@ -2,7 +2,13 @@
 
 user=$1
 
-read -p "Really remove user '$user'?" x
+read -p "Really remove user '$user'? (Enter 'Y' to confirm.) " reply
+
+if [ "$reply" != "Y" ]
+then
+    echo >&2 "Aborting."
+    exit
+fi
 
 dn="cn=$user,ou=members,dc=feministwiki,dc=org"
 
